name: example.yml
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  Example:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 检查仓库文件
        run: ls -al

      - name: 设置node环境
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: node --version

      - name: 安装依赖
        run: npm install

      - name: 运行测试
        run: node ./src/example.js
